### PR TITLE
feat: add KSQL server, resolves #43

### LINKED ISSUE #43: Add KSQL Server

### PR DESCRIPTION
**Pull request by devshawn**
Adds a KSQL server to the `full-stack.yml`. It exposes port `8088`, the default KSQL port. You can access it utilizing the ksql CLI by typing `ksql` in a terminal. Resolves issue #43. 😄

### CODE REVIEW

**Comment by simplesteph** [comment]
@devshawn  thanks for this! The CI fails, can you please look into it?

**Comment by devshawn** [comment]
No problem! Sure thing, I'll check it out after work today.

**Comment by devshawn** [comment]
@simplesteph - fixed the CI build. Didn't realize the test checked the number of containers running. :)

**Comment by simplesteph** [comment]
@devshawn  yes that's what I suspected, small tip to ensure that the docker-compose files aren't broken :) thanks for fixing that!

**Pull request merged**
