### PR TITLE
feat: Upgrade zoonavigator to 0.8.0

### PR DESCRIPTION
**Pull request by retorres**

### CODE REVIEW

**Comment by simplesteph** [comment]
Thanks! can you check why the build is failing?

**Comment by retorres** [comment]
> Thanks! can you check why the build is failing?

Yes, its the task on travis-ci....
update it from:
./test.sh full-stack.yml 11
to:
./test.sh full-stack.yml 10

**Comment by simplesteph** [comment]
If you update the test it’s all good :)

**Comment by retorres** [comment]
Sup Steph, done!

Im new with travis, in need to study it.

**Comment by simplesteph** [comment]
Thanks for the PR :)

**Pull request merged**
